# 不可恢复错误

宏`panic!`主要用于测试，以及不可恢复性(unrecoverable)错误。

> 通常不可恢复性错误代表bug，或系统环境变量故障。

&nbsp;

```rust
struct X {
    n: i32,
}

impl Drop for X {
    fn drop(&mut self) {
        println!("Dropping {}!", self.n);
    }
}

fn test() {
    let _x = X{n: 2};
    panic!("panic test.");
}

fn main() {
    let _y = X{n: 1};
    test();
}
```

```rust
root@8d75790f92f5:~/rs/closure/src# cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `/root/rs/closure/target/debug/closure`
thread 'main' panicked at 'panic test.', src/main.rs:13:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dropping 2!
Dropping 1!
```

```rust
root@8d75790f92f5:~/rs/closure/src# RUST_BACKTRACE=1 cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `/root/rs/closure/target/debug/closure`
thread 'main' panicked at 'panic test.', src/main.rs:13:5
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:519:12
   1: closure::test
             at ./main.rs:13:5
   2: closure::main
             at ./main.rs:18:5
   3: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Dropping 2!
Dropping 1!
```

可在Cargo.toml中设置以终止(abort)代替展开，不回溯清理，直接终止进程。

&nbsp;

> 对于部署的发型版(release version)，展开信息可能没什么用。
>
> 还可删除(strip)符号表，避免错误信息造成泄漏。

&nbsp;

```rust
# Cargo.toml

[profile.release]
panic = 'abort'
```

&nbsp;

```rust
root@8d75790f92f5:~/rs/closure/src# cargo r --release
    Finished release [optimized] target(s) in 0.05s
     Running `/root/rs/closure/target/release/closure`
thread 'main' panicked at 'panic test.', src/main.rs:13:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

&nbsp;

## 常用场景

除直接调用外，以下场景也会引发panic!错误。

* 越界访问
* 被除以零
* Option.unwrap/expect(可选值)
* Result.unwarp/expect(返回值)

> unwrap和expect区别？
> 
> `expect` 与 `unwrap` 的使用方式一样：返回`OK`或调用`panic!`宏
> 
> `expect` 用来调用 `panic!` 的错误信息将会作为参数传递给 `expect` ，而不像`unwrap` 那样使用默认的 `panic!` 信息。

&nbsp;

## 分歧函数

分歧函数(diverging)表示永远不会返回(never return)的函数。

* 无限循环`main loop`
* 包装`panic!`，用于调试或跟踪调用堆栈
* 紧急终止进程

```rust
fn test() -> ! {            // ! 分歧函数
    panic!("This function never returns!");
}

fn main() {
    let _x = test();
            // ------ any code following this expression is unreachable 

    let y = 0x64;
            // ^^^^^^^^^^^^^ unreachable statement
    println!("{:?}", y);
}
```
